
version: 2

models:
    - name: main_table
      description: "Main table"
    - name: region_per_highest_deaths
      description: "regions with more deaths model"
    - name: active_cases
      description: "total active cases per day model"


